---
title: "Simple document"
output: github_document
---

I'm an R Markdown document! 
```{r, echo =FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

# Import some data in section 0

I want to import 'FAS_litters.csv'.

```{r}
litters_df = read_csv("data/FAS_litters.csv")

```

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
```

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

```{r, evol = FALSE}
view(litters_df)
```

here's the sk
```{r}
skimr::skim(litters_df)
```

## Arguments in 'read_csv'

```{r}
litters_df =
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE,
    na = "low8"
  )
```

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```



## Reading from excel

Read MLB data

```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
```

LotR words is next

```{r}
fellow_df = read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

Try to read sas file and didn't

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```


## how do I export data
```{r}
write_csv(fellow_df, "data/LotR_Words.xlsx")
```