---
title: "manipulation 928"
output: github_document
---

I'm an R Markdown document! 
```{r, echo =FALSE, message=FALSE}
library(tidyverse)
```

# Import some data in section 0

I want to import 'FAS_litters.csv'.

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)


```

## select

```{r}
select(litters_df, group, litter_number)
select(litters_df, group, starts_with("pups"))

select(litters_df, -litter_number)

rename(litters_df, GROUP = group)
select(litters_df, litter_number, everything())
select(litters_df, litter_number, sex, pd_ears)
pull(litters_df, group) # select one col
```


## filter
```{r}
filter(litters_df, gd_of_birth == 20)
filter(litters_df, group == "Con7") # use "==" to filter

filter(litters_df, gd0_weight > 23) # for two condition, use "&" for "and", and use "|" for "or".

filter(litters_df, !(group == "Con7"))

filter(litters_df, group %in% c("Con7", "Con8"))

#drop missing value
drop_na(litters_df)

```

## mutate
```{r}
mutate(litters_df, weight_change = gd18_weight - gd0_weight)
```

```{r}
litters_data_raw = read_csv("data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_select = select(litters_clean_name, group)
```

```{r}
litter_df =
  read_csv("data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(group, pups_survive) %>% 
  filter(group == "Con7")


litters_df = 
  read_csv("data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    weight_change = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  ) %>% 
  drop_na(weight_change)
  
```
